In [17]:
# ===========
# INSTALAÇÃO DE BIBLIOTECAS   
# ===========

%pip install -q pandas # manipulação e análise de dados
%pip install -q numpy # cálculos e operações numéricas
%pip install -q matplotlib # criação de gráficos
%pip install -q seaborn # visualizações estatísticas

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Invalid requirement: '#': Expected package name at the start of dependency specifier
    #
    ^

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Invalid requirement: '#': Expected package name at the start of dependency specifier
    #
    ^

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Invalid requirement: '#': Expected package name at the start of dependency specifier
    #
    ^

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Invalid requirement: '#': Expected package name at the start of dependency specifier
    #
    ^

In [18]:
# ===========
# IMPORTAÇÃO DE BIBLIOTECAS UTILIZADAS
# ===========
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import csv


# ===========
# VALIDAÇÃO DAS IMPORTAÇÕES E VERSÕES INSTALADAS
# ===========
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Matplotlib:", plt.matplotlib.__version__)
print("Seaborn:", sns.__version__)

Pandas: 3.0.5
NumPy: 2.5.1
Matplotlib: 3.11.1
Seaborn: 0.13.2

In [19]:
# PRIMEIRA LEITURA DO ARQUIVO BASE SERÁ UTILIZANDO O PYTHON DIRETAMENTE


# ===========
# LEITURA ARQUIVO BASEVAREJO.CSV
# ===========
with open("dataset/BaseVarejo.csv", encoding="utf-8") as arquivo:
    leitor = csv.DictReader(arquivo)
    colunas = leitor.fieldnames
    vendas = list(leitor)


# ===========
# CONFERÊNCIA DA LEITURA
# ===========
print("VALIDAÇÃO LEITURA ARQUIVO .CSV\n")
print(f"Arquivo lido com sucesso!")
print(f"Quantidade de registros: {len(vendas)}")
print(f"Quantidade de colunas: {len(colunas)}")
print("Colunas:", colunas)
print("\nPrimeiro registro:")
print(vendas[0])

VALIDAÇÃO LEITURA ARQUIVO .CSV

Arquivo lido com sucesso!
Quantidade de registros: 830000
Quantidade de colunas: 1
Colunas: ['DATA;CO_ID;CL_ID;CL_GENERO;CL_EC;CL_FHL;CL_SEG;PR_ID;PR_CAT;PR_NOME;;;;']

Primeiro registro:
{'DATA;CO_ID;CL_ID;CL_GENERO;CL_EC;CL_FHL;CL_SEG;PR_ID;PR_CAT;PR_NOME;;;;': '01/02/2019;1000;534;M;4;1;C;67;BEBIDAS;REFRIGERANTE GUARANA;;;;'}

Com a primeira validação, é possível verificar que o `DictReader` está lendo o arquivo, porém está entendendo que a linha inteira é uma única coluna:
```
print(f"Quantidade de colunas: {len(colunas)}")
Quantidade de colunas: 1
```
Isso ocorre, pois o CSV está separando as informações com `;` e não `,`.

Dessa forma, é necessário informar ao `DictReader` que o limitador é `;`

In [20]:
# ===========
# LEITURA DA BASE CORRIGINDO O DELIMITADOR
# ===========
with open("dataset/BaseVarejo.csv", encoding="utf-8") as arquivo:
    leitor = csv.DictReader(arquivo, delimiter=";")
    colunas = leitor.fieldnames
    vendas = list(leitor)


# ===========
# NOVA CONFERÊNCIA DA LEITURA
# ===========
print("VALIDAÇÃO LEITURA ARQUIVO .CSV\n")
print(f"Arquivo lido com sucesso!")
print(f"Quantidade de registros: {len(vendas)}")
print(f"Quantidade de colunas: {len(colunas)}")
print("Colunas:", colunas)
print("\nPrimeiro registro:")
print(vendas[0])

VALIDAÇÃO LEITURA ARQUIVO .CSV

Arquivo lido com sucesso!
Quantidade de registros: 830000
Quantidade de colunas: 14
Colunas: ['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME', '', '', '', '']

Primeiro registro:
{'DATA': '01/02/2019', 'CO_ID': '1000', 'CL_ID': '534', 'CL_GENERO': 'M', 'CL_EC': '4', 'CL_FHL': '1', 'CL_SEG': 'C', 'PR_ID': '67', 'PR_CAT': 'BEBIDAS', 'PR_NOME': 'REFRIGERANTE GUARANA', '': ''}

In [21]:
# ===========
# REALIZANDO A LEITURA UTILIZANDO PANDAS
# ===========
df_original = pd.read_csv("dataset/BaseVarejo.csv", encoding="utf-8", delimiter=";") # COLOCANDO O DELIMITADOR ';' 
display(df_original) # MOSTRANDO DATAFRAME CRIADO

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,NaN,NaN,NaN,NaN
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,NaN,NaN,NaN,NaN

In [22]:
# ===========
# REALIZANDO AS VISUALIZAÇÕES INICIAIS
# ===========
print("VISUALIZAÇÕES INICIAIS\n")

# .shape() MOSTRA O NÚMERO DE LINHAS E COLUNAS
print(f"Quantidade de registros: {df_original.shape[0]}") # MOSTRA O NÚMERO DE LINHAS
print(f"Quantidade de colunas: {df_original.shape[1]}") # MOSTRA O NÚMERO DE COLUNAS

print("\nColunas:")
print(df_original.columns.tolist()) # CRIANDO UMA LISTA COM OS NOMES DA COLUNAS

print("\nPrimeiros 5 registros:")
display(df_original.head())

print("\nÚltimos 5 registros:")
display(df_original.tail())

VISUALIZAÇÕES INICIAIS

Quantidade de registros: 830000
Quantidade de colunas: 14

Colunas:
['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

Primeiros 5 registros:

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

Últimos 5 registros:

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,NaN,NaN,NaN,NaN
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,NaN,NaN,NaN,NaN

Nesse momento foi verifcado que o arquivo base possui 4 (quatro) colunas sem títulos:  
`Unnamed: 10` `Unnamed: 11` `Unnamed: 12` `Unnamed: 13`  
Necessário realizar novas validações para verificar possiveis registros.

In [23]:
# ===========
# CRIANDO NOVO df PARA AS COLUNAS SEM TÍTULO
# ===========
df_columns = df_original[["Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13"]]

display(df_columns)

        Unnamed: 10  Unnamed: 11  Unnamed: 12  Unnamed: 13
0               NaN          NaN          NaN          NaN
1               NaN          NaN          NaN          NaN
2               NaN          NaN          NaN          NaN
3               NaN          NaN          NaN          NaN
4               NaN          NaN          NaN          NaN
...             ...          ...          ...          ...
829995          NaN          NaN          NaN          NaN
829996          NaN          NaN          NaN          NaN
829997          NaN          NaN          NaN          NaN
829998          NaN          NaN          NaN          NaN
829999          NaN          NaN          NaN          NaN

[830000 rows x 4 columns]

In [28]:
# ===========
# VERIFICAÇÃO df_columns
# ===========
df_columns.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 10  0 non-null      float64
 1   Unnamed: 11  0 non-null      float64
 2   Unnamed: 12  0 non-null      float64
 3   Unnamed: 13  0 non-null      float64
dtypes: float64(4)
memory usage: 25.3 MB

As colunas não possuem valores preenchidos (`0 non-null`) e, portanto, não apresentam informações úteis para a análise. Elas serão removidas do `df_copia`, preservando o `df_original` para referência.

In [ ]:
# ===========
# CRIANDO NOVO df PARA ALTERAÇÕES
# ===========
df_copia = df_original.copy()


# ===========
# REMOVENDO AS COLUNAS SEM INFORMAÇÕES
# ===========
df_copia = df_copia.dropna(axis=1, how="all")

print("Qtd. Colunas antes da limpeza:", df_original.shape)
print("Qtd. Colunas após a limpeza:", df_copia.shape)
print(df_copia.columns.tolist())

Qtd. Colunas antes da limpeza: (830000, 14)
Qtd. Colunas após a limpeza: (830000, 10)
['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME']

In [ ]:
# ===========
# CRIANDO VALIDAÇÕES DO df_copia
# ===========
df_copia.info() # VERIFICANDO AS INFORMAÇÕES DE NULOS E TIPO DE CADA COLUNA
display(df_copia.isnull().sum()) # VALIDANDO O TOTAL DE NULOS DE CADA COLUNA

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       830000 non-null  str
 1   CO_ID      830000 non-null  int64
 2   CL_ID      830000 non-null  int64
 3   CL_GENERO  830000 non-null  str
 4   CL_EC      830000 non-null  int64
 5   CL_FHL     830000 non-null  int64
 6   CL_SEG     830000 non-null  str
 7   PR_ID      830000 non-null  int64
 8   PR_CAT     830000 non-null  str
 9   PR_NOME    830000 non-null  str
dtypes: int64(5), str(5)
memory usage: 63.3 MB

DATA         0
CO_ID        0
CL_ID        0
CL_GENERO    0
CL_EC        0
CL_FHL       0
CL_SEG       0
PR_ID        0
PR_CAT       0
PR_NOME      0
dtype: int64

Foram identificadas quatro colunas totalmente vazias (`Unnamed: 10` a `Unnamed: 13`), que foram removidas por não apresentarem informação. Após a remoção, a base passou a conter 830.000 registros e 10 colunas, **sem valores nulos**.